/* ============================================================
   CARD STUFF YES — BATTLE EVENTS MODULE
   ============================================================

   This module handles events generated by battles/games.

   It provides a simple event system so the server can later
   broadcast things such as:

   - Player joined
   - Game started
   - Turn changed
   - Card played
   - Player eliminated
   - Battle ended

   This keeps event/broadcast logic out of battles.js.

   ============================================================ */


/* ============================================================
   CREATE BATTLE EVENTS MODULE
   ============================================================ */

function createBattleEventsModule() {

    /* ========================================================
       EVENT STORAGE
       ======================================================== */

    /*
     * Map:
     *
     *     eventName -> Set of listeners
     */

    const listeners =
        new Map();


    /* ========================================================
       SUBSCRIBE
       ======================================================== */

    function on(
        eventName,
        listener
    ) {

        if (
            typeof eventName !==
            "string"
        ) {

            throw new Error(
                "Event name must be a string."
            );

        }


        if (
            typeof listener !==
            "function"
        ) {

            throw new Error(
                "Event listener must be a function."
            );

        }


        if (
            !listeners.has(
                eventName
            )
        ) {

            listeners.set(
                eventName,
                new Set()
            );

        }


        const eventListeners =
            listeners.get(
                eventName
            );


        eventListeners.add(
            listener
        );


        /*
         * Return an unsubscribe function.
         */

        return () => {

            off(
                eventName,
                listener
            );

        };

    }


    /* ========================================================
       UNSUBSCRIBE
       ======================================================== */

    function off(
        eventName,
        listener
    ) {

        const eventListeners =
            listeners.get(
                eventName
            );


        if (!eventListeners) {

            return false;

        }


        const removed =
            eventListeners.delete(
                listener
            );


        if (
            eventListeners.size ===
            0
        ) {

            listeners.delete(
                eventName
            );

        }


        return removed;

    }


    /* ========================================================
       EMIT EVENT
       ======================================================== */

    function emit(
        eventName,
        data = {}
    ) {

        const eventListeners =
            listeners.get(
                eventName
            );


        if (!eventListeners) {

            return;

        }


        for (
            const listener
            of eventListeners
        ) {

            try {

                listener(
                    data
                );

            } catch (error) {

                /*
                 * One broken listener should not prevent other
                 * listeners from receiving the event.
                 */

                console.error(
                    `Battle event listener error (${eventName}):`,
                    error
                );

            }

        }

    }


    /* ========================================================
       CLEAR LISTENERS
       ======================================================== */

    function clear(
        eventName = null
    ) {

        if (
            eventName === null
        ) {

            listeners.clear();

            return;

        }


        listeners.delete(
            eventName
        );

    }


    /* ========================================================
       GET LISTENER COUNT
       ======================================================== */

    function getListenerCount(
        eventName
    ) {

        const eventListeners =
            listeners.get(
                eventName
            );


        if (!eventListeners) {

            return 0;

        }


        return eventListeners.size;

    }


    /* ========================================================
       COMMON BATTLE EVENTS
       ======================================================== */

    /*
     * These constants prevent spelling mistakes when other
     * modules emit events.
     */

    const EVENTS = {

        PLAYER_JOINED:
            "playerJoined",

        PLAYER_LEFT:
            "playerLeft",

        GAME_CREATED:
            "gameCreated",

        GAME_STARTED:
            "gameStarted",

        TURN_STARTED:
            "turnStarted",

        TURN_ENDED:
            "turnEnded",

        CARD_PLAYED:
            "cardPlayed",

        PLAYER_ELIMINATED:
            "playerEliminated",

        GAME_ENDED:
            "gameEnded",

        BATTLE_ENDED:
            "battleEnded"

    };


    /* ========================================================
       RETURN MODULE API
       ======================================================== */

    return {

        EVENTS,

        on,

        off,

        emit,

        clear,

        getListenerCount

    };

}


/* ============================================================
   EXPORTS
   ============================================================ */

module.exports = {

    createBattleEventsModule

};
