name: Deploy Server to GitHub Pages

on:
  push:
    branches:
      - Server

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy:

    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Server
        uses: actions/upload-pages-artifact@v5
        with:
          path: './Server'

      - name: Deploy
        uses: actions/deploy-pages@v4
